### ISSUE TITLE
DeletionPolicy:Snapshot cannot be specified for a cluster instance, use deletion policy on the cluster instead.

### ISSUE THREAD

**Issue by tzvetkovg** [awslabs/aws-cloudformation-templates#16] opened 2017-07-15 17:07 UTC
There's seems to be an issue with cloudformation in eu-west-1 (ireland region) when creating/modifying database resources. Please see the following threads
https://stackoverflow.com/questions/45117089/deletionpolicysnapshot-cannot-be-specified-for-a-cluster-instance-use-deletion

https://forums.aws.amazon.com/thread.jspa?threadID=259843&tstart=0

Is there any resolution?

**Comment by LRomandine** [comment] 2017-07-15 17:36
Please log a support ticket through the AWS console to get a definitive answer.

Since the template works in most regions it doesn't sound like a template issue but possibly an issue caused by regions not having feature parity.  For that reason I am closing this issue.

If the answer from AWS support does involve a change to the template please open a new issue and include the text of their response; or better yet, fork the repo, fix it, and open a pull request.

**Closed by LRomandine** 2017-07-15 17:36 UTC
